# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: cidr-calculator

before:
  hooks:
    - go mod tidy

builds:
  - id: cidr-calculator
    main: .
    binary: cidr-calculator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/smford/cidr-calculator/internal/cli.Version={{ .Version }}
      - -X github.com/smford/cidr-calculator/internal/cli.Commit={{ .Commit }}
      - -X github.com/smford/cidr-calculator/internal/cli.BuildDate={{ .Date }}

archives:
  - id: cidr-calculator
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge branch"
